//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cadastro_X
{
    using System;
    using System.Collections.Generic;
    
    public partial class Funcionarios
    {
        public int Id_Func { get; set; }
        public string Nome { get; set; }
        public string Email { get; set; }
        public string CPF { get; set; }
        public string Endereco { get; set; }
        public string Bairro { get; set; }
        public string CEP { get; set; }
        public string Cidade { get; set; }
        public string UF { get; set; }
        public Nullable<int> Departamento { get; set; }
        public System.DateTime Dtt_Record { get; set; }
        public Nullable<System.DateTime> Dtt_Birth { get; set; }
    }
}
